Anahi su patch 1
education/codespaces-project-template-js pull request #55
Opened 2023-06-30 22:57 UTC by AnahiSU

2023-06-30 22:58 UTC, AnahiSU reviewed
Done

2023-07-07 19:47 UTC, glaucia86 approved these changes
LGTM

2023-07-08 00:39 UTC, abrilurena requested changes
¡Mil gracias, Anahí por tu ayuda y tiempo al traducir esto en español! He hecho algunos comentarios, cualquier pregunta que tengas por favor no dudes en escribirme 😃

2023-07-08 00:39 UTC, abrilurena commented on translations/es/README.md
> +_Ayuda_: Entu archivo `styles.css`, usa comentarios para decirle a Copilot lo que quieres que haga. Revisa lo que te sugiere, complementa tus instrucciones, y fijate como te guía en conseguir crear t
```suggestion
_Ayuda_: En tu archivo `styles.css`, usa comentarios para decirle a Copilot lo que quieres que haga. Revisa lo que te sugiere, complementa tus instrucciones, y fíjate como te guía en conseguir crear tu flecha para rebotar. 
```

2023-07-08 00:39 UTC, abrilurena commented on translations/es/README.md
> +<br/>
```suggestion
<br/>

```

2023-07-08 00:39 UTC, abrilurena commented on translations/es/README.md
> +1. Presiona `enter` luego de la línea de importación para que Copilot sugiera el código para crear tu componente `Education` . Presiona `tab` para aceptar la solución o `crtl` + `enter` para ver toda
```suggestion
1. Presiona `enter` luego de la línea para que Copilot sugiera el código para crear tu componente `Education` . Presiona `tab` para aceptar la solución o `crtl` + `enter` para ver todas las sugerencias de Copilot y seleccionar la que mejor funcione para tí. 
```

2023-07-08 00:39 UTC, abrilurena commented on translations/es/README.md
> +    Minimamente, necesitarás un `const` definido en el componente `Education` exportado (un ejemplo abajo). El resto depende de tí. Experimenta con Copilot, enlazandolo con lo que tu desees construir
```suggestion
    Al menos, necesitarás un `const` definido y el componente `Education` exportado (un ejemplo abajo). El resto depende de tí. Experimenta con Copilot, enlazándolo con lo que tu desees construir. 
```

2023-07-08 00:39 UTC, abrilurena commented on translations/es/README.md
> +Ahora que estás familiarizado en que Copilot puede no solamente escribir código rápido, pero te da unas sugerencias para ahorrar tiempo buscando soluciones.
que opinas? :D 
```suggestion
Ahora sabes que GitHub Copilot puede escribir código rápido y también te da unas sugerencias para ahorrar tiempo buscando soluciones.
```

2023-07-08 00:39 UTC, abrilurena commented on translations/es/README.md
>  1. [Personaliza el sitio de tu portafolio](#personaliza-tu-pagina-web-en-3-pasos)
creo que no funciona el href
```suggestion
1. [Personaliza el sitio de tu portafolio](#-personaliza-tu-pagina-web-en-3-pasos)
```

2023-07-08 00:39 UTC, abrilurena commented on translations/es/README.md
>  1. [Sube tu Portafolio a la nube](#subir-tu-aplicacion-web)
```suggestion
1. [Sube tu Portafolio a la nube](#-subir-tu-aplicacion-web)

```

2023-07-09 00:45 UTC, AnahiSU commented on translations/es/README.md
> +En esta plantilla tenemos el entorno de desarrollo y una base predeterminada lista para usar. Con todo ello ya podrás iniciar inmediatamente tu entorno de [Codespace](https://github.com/features/code
Gracias por las correcciones Abril :D

2023-07-09 00:51 UTC, AnahiSU reviewed
Abril's corrections reviewed

2023-07-10 13:19 UTC, alfredodeza approved these changes

2023-07-10 13:19 UTC, alfredodeza commented
Gracias @AnahiSU 🚀

2023-07-10 13:19 UTC, merged